language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -e .
  - pip install mock "pytest>=3" pytest-cov coveralls
script: pytest
after_success: if [[ $ENV == python=3.6* ]]; then coveralls; fi
