language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
install:
  - pip install -e .
  - pip install mock "pytest>=3" pytest-cov
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; pip install coveralls; fi
script: pytest
after_success: if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then coveralls; fi
